allowlist:
  # Firebase client-side config dosyaları (anahtarlar istemci tarafında dağıtılır; erişim, backend kuralları ve API kısıtlarıyla korunmalıdır)
  paths:
    - "lib/firebase_options.dart"
    - "android/app/google-services.json"