include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    one_member_abstracts: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  plugins:
    - dart_code_metrics

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    unnecessary_this: true
    prefer_final_fields: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    directives_ordering: true
    unnecessary_await_in_return: true

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 10
    maximum-nesting-level: 4
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
    - "**/*.g.dart"

  rules:
    # Ortak kurallar
    - no-boolean-literal-compare
    - no-empty-block
    # - prefer-trailing-comma
    - prefer-conditional-expressions
    - avoid-nested-conditional-expressions
    - avoid-unused-parameters
    # - member-ordering


  rules-exclude:
    - test/**
