workflows:
  ci:
    name: CI
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.kamurandev.wedlist.wedlist # Projedeki iOS Bundle ID
      groups:
        - app_store_connect
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Format check
        script: dart format --set-exit-if-changed .
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        script: flutter test --test-randomize-ordering-seed=random
      - name: Build Android debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  android_release:
    name: Android Release (AAB)
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - keystore_credentials
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Format check
        script: dart format --set-exit-if-changed .
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        script: flutter test --test-randomize-ordering-seed=random
      - name: Prepare Android keystore
        script: |
          echo "$ANDROID_KEYSTORE" | base64 --decode > android/app/keystore.jks
          cat > android/key.properties <<EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=app/keystore.jks
          EOF
      - name: Build Android App Bundle (release)
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab

  ios_release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CodeMagicKey
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.kamurandev.wedlist.wedlist
      vars:
        APP_STORE_APPLE_ID: 6752911302
        TEAM_ID: BCX89L2UF2
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean & get packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..
      - name: Apply signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" --platform=IOS 2>/dev/null || echo 0)
          [[ "$LATEST" =~ ^[0-9]+$ ]] || LATEST=0
          BUILD_NUMBER=$((LATEST + 1))
          echo "Using build number: $BUILD_NUMBER"
          # Re-apply signing right before the build (Flutter may upgrade project files)
          xcode-project use-profiles
          # Export options with explicit Team ID for reliability
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>teamID</key><string>$TEAM_ID</string>
            <key>uploadBitcode</key><false/>
            <key>uploadSymbols</key><true/>
          </dict>
          </plist>
          EOF
          flutter build ipa --release \
            --export-options-plist=export_options.plist \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
      - name: List artifacts
        script: |
          find build/ios/ipa -type f -print || true
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - kamuran.software@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  # ios_release_distribution:
  #   name: iOS Release Distribution
  #   integrations:
  #     app_store_connect: CodeMagicKey
  #   max_build_duration: 120
  #   instance_type: mac_mini_m2
  #   environment:
  #     ios_signing:
  #       provisioning_profiles:
  #         - wedlist-appstore-profile
  #       certificates:
  #         - wedlist-distribution
  #     vars:
  #       APP_STORE_APPLE_ID: 6752911302
  #       TEAM_ID: BCX89L2UF2
  #     flutter: stable
  #     xcode: latest
  #     cocoapods: default
  #   scripts:
  #     - name: Set up code signing settings on Xcode project
  #       script: xcode-project use-profiles
  #     - name: Get Flutter packages
  #       script: flutter pub get
  #     - name: Install pods
  #       script: |
  #         cd ios
  #         rm -rf Pods Podfile.lock
  #         pod install --repo-update
  #         cd ..
  #     - name: Flutter build ipa
  #       script: |
  #         BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
  #         flutter build ipa --release \
  #           --build-name=1.0.$BUILD_NUMBER \
  #           --build-number=$BUILD_NUMBER
  #   artifacts:
  #     - build/ios/ipa/*.ipa
  #     - /tmp/xcodebuild_logs/*.log
  #     - flutter_drive.log
  #   publishing:
  #     email:
  #       recipients:
  #         - kamuran.software@gmail.com
  #       notify:
  #         success: true
  #         failure: false
  #     app_store_connect:
  #       auth: integration
  #       submit_to_testflight: true
  #       submit_to_app_store: false
