workflows:
  ci:
    name: CI
    max_build_duration: 45
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Format check
        script: dart format --set-exit-if-changed .
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        script: flutter test --test-randomize-ordering-seed=random
      - name: Build Android debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  android_release:
    name: Android Release (AAB)
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - keystore_credentials # Codemagic UI'da oluşturacağınız env grubu (aşağıdaki env'leri içermeli)
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Format check
        script: dart format --set-exit-if-changed .
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        script: flutter test --test-randomize-ordering-seed=random
      - name: Prepare Android keystore
        script: |
          # Aşağıdaki env değişkenlerini Codemagic'de tanımlayın:
          # ANDROID_KEYSTORE (base64), ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD
          echo "$ANDROID_KEYSTORE" | base64 --decode > android/app/keystore.jks
          cat > android/key.properties <<EOF
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          storeFile=app/keystore.jks
          EOF
      - name: Build Android App Bundle (release)
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab

  # iOS için imzalama gereklidir. Codemagic Automatic Code Signing ile
  # kolayca kurulabilir. Hazır olduğunuzda ayrı bir iOS workflow'u ekleyebiliriz.
  ios_debug:
    name: iOS Debug (Automatic signing)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.kamurandev.wedlist.wedlist # Projedeki iOS Bundle ID
      groups:
        - app_store_connect # Codemagic UI’da APP_STORE_CONNECT_* değişkenlerini tanımlayın
        # Gerekirse 'certificate_private_key' grubuna CERTIFICATE_PRIVATE_KEY ekleyin
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Format check
        script: dart format --set-exit-if-changed .
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        script: flutter test --test-randomize-ordering-seed=random
      - name: Fetch iOS signing files (Development)
        script: |
          # Aşağıdaki üç env var Codemagic’te tanımlı olmalı:
          # APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_PRIVATE_KEY (.p8 içeriği)
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Use provisioning profiles
        script: xcode-project use-profiles
      - name: Build iOS IPA (debug/development)
        script: flutter build ipa --debug
    artifacts:
      - build/ios/ipa/*.ipa

  ios_release:
    name: iOS Release (App Store, automatic signing)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.kamurandev.wedlist.wedlist
      groups:
        - app_store_connect
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Format check
        script: dart format --set-exit-if-changed .
      - name: Analyze
        script: flutter analyze
      - name: Run tests
        script: flutter test --test-randomize-ordering-seed=random
      - name: Fetch iOS signing files (App Store)
        script: |
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Use provisioning profiles
        script: xcode-project use-profiles
      - name: Build iOS IPA (release)
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
