// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfyqODIteENj1cG8WK5eqfm103HGbM4E',
    appId: '1:835425852476:web:6e9ca783d3af5ac2ebb739',
    messagingSenderId: '835425852476',
    projectId: 'wedlist-bb058',
    authDomain: 'wedlist-bb058.firebaseapp.com',
    databaseURL:
        'https://wedlist-bb058-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wedlist-bb058.firebasestorage.app',
    measurementId: 'G-GDJ0FH69SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfANJgCOZ0J9o5n6u-eG2S8gysPGG6fA',
    appId: '1:835425852476:android:91dddf42db3f33f5ebb739',
    messagingSenderId: '835425852476',
    projectId: 'wedlist-bb058',
    databaseURL:
        'https://wedlist-bb058-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wedlist-bb058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7rMhL-jD9Iop_Bosfz9vDEw92w4sXwM',
    appId: '1:835425852476:ios:4f4af773a2a63d9aebb739',
    messagingSenderId: '835425852476',
    projectId: 'wedlist-bb058',
    databaseURL:
        'https://wedlist-bb058-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wedlist-bb058.firebasestorage.app',
    androidClientId:
        '835425852476-4ant65t2dcald209b0h3en4nevpmvha7.apps.googleusercontent.com',
    iosClientId:
        '835425852476-jqu8kcsr64k9167ua0tfil7oogre6714.apps.googleusercontent.com',
    iosBundleId: 'com.kamurandev.wedlist.wedlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi7rMhL-jD9Iop_Bosfz9vDEw92w4sXwM',
    appId: '1:835425852476:ios:4f4af773a2a63d9aebb739',
    messagingSenderId: '835425852476',
    projectId: 'wedlist-bb058',
    databaseURL:
        'https://wedlist-bb058-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wedlist-bb058.firebasestorage.app',
    androidClientId:
        '835425852476-4ant65t2dcald209b0h3en4nevpmvha7.apps.googleusercontent.com',
    iosClientId:
        '835425852476-jqu8kcsr64k9167ua0tfil7oogre6714.apps.googleusercontent.com',
    iosBundleId: 'com.kamurandev.wedlist.wedlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcfyqODIteENj1cG8WK5eqfm103HGbM4E',
    appId: '1:835425852476:web:7efb386fb68ccb5febb739',
    messagingSenderId: '835425852476',
    projectId: 'wedlist-bb058',
    authDomain: 'wedlist-bb058.firebaseapp.com',
    databaseURL:
        'https://wedlist-bb058-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wedlist-bb058.firebasestorage.app',
    measurementId: 'G-QWG04B3PMT',
  );
}
